#!/bin/sh

rm -f *~ src/*~ src/*.o src/*.so src/symbols.rds man/*~ R/*~ config.* src/Makevars src/config.h 
if [ -e src/Netica/NeticaAPI.zip ]; then
    rm -f src/Netica/NeticaAPI.zip src/Netica/Makefile
    rm -rf src/Netica/Netica_API_*
fi
