## The purpose of this makefile is to download and install the Netica
## API from the Norsys website, thus making its installation
## transparent to the user.

APIurlLinux = https://norsys.com/downloads/NeticaAPI_Linux_607.zip
APIurlWin = https://norsys.com/downloads/NeticaAPI_Win_510.zip
APIurlMac = https://norsys.com/downloads/NeticaAPI_Mac.zip


NeticaAPI:
	
