StartNetica()
print(NeticaVersion())
net1 <- CreateNetwork("Untitled")
print(net1)
nets <- CreateNetwork(paste("Untitled",2:3,sep=""))
print(nets)
net2 <- GetNamedNets("Untitled2")
print(net2)
fish <- GetNamedNets("fish")
print(fish)
netn <- GetNthNet(2)
print(netn)
netnn <- GetNthNet(c(0,2))
print(netnn)
netnnn <- GetNthNet(17)
print(netnnn)
netd <- DeleteNetwork(net2)
print(netd)
netdd <- GetNamedNets("Untitled2")
print(netdd)
netn <- GetNthNet(1)
print(netn)
netc <- CopyNets(netnn,paste("Copies",2:3,sep=""))
print(netc)
netnn <- GetNthNet(0:3)
print(netnn)
StopNetica()
