StartNetica()
print(NeticaVersion())
net1 <- CreateNetwork("Untitled")
print(net1)
nets <- CreateNetwork(paste("Untitled",2:3,sep=""))
print(nets)
DeleteNetwork(net1)
print(net1)
netn <- GetNthNet(2)
print(netn)
netn <- GetNthNet(3)
print(netn)
netu <- GetNamedNets("Untitled2")
print(netu)
netc <- CopyiedNets(nets,paste("Copies",2:3,sep=""))
StopNetica()
